// ⚽ Auto-generated by scripts/rename-logos.js
// Do not edit manually — update logos in /public/images/club-logos and re-run the script.
const TEAM_LOGO_MAP: Record<string, string> = {
  "AFC Bournemouth": "afc-bournemouth",
  "Arsenal FC": "arsenal-fc",
  "Arsenal": "arsenal-fc",
  "Aston Villa": "aston-villa",
  "Brentford FC": "brentford-fc",
  "Brentford": "brentford-fc",
  "Brighton & Hove Albion": "brighton-and-hove-albion",
  "Burnley FC": "burnley-fc",
  "Burnley": "burnley-fc",
  "Chelsea FC": "chelsea-fc",
  "Chelsea": "chelsea-fc",
  "Crystal Palace": "crystal-palace",
  "Everton FC": "everton-fc",
  "Everton": "everton-fc",
  "Fulham FC": "fulham-fc",
  "Fulham": "fulham-fc",
  "Leeds United": "leeds-united",
  "Liverpool FC": "liverpool-fc",
  "Liverpool": "liverpool-fc",
  "Manchester City": "manchester-city",
  "Manchester United": "manchester-united",
  "Newcastle United": "newcastle-united",
  "Nottingham Forest": "nottingham-forest",
  "Sunderland AFC": "sunderland-afc",
  "Sunderland": "sunderland-afc",
  "Tottenham Hotspur": "tottenham-hotspur",
  "West Ham United": "west-ham-united",
  "Wolverhampton Wanderers": "wolverhampton-wanderers",
  "Man Utd": "manchester-united",
  "Man United": "manchester-united",
  "Spurs": "tottenham-hotspur",
  "Man City": "manchester-city",
  "Nott'm Forest": "nottingham-forest",
  "Wolves": "wolverhampton-wanderers",
  "Brighton": "brighton-and-hove-albion",
  "Leeds": "leeds-united",
  "West Ham": "west-ham-united",
  "Bournemouth": "afc-bournemouth"
};

export const getTeamLogoPath = (
  teamName: string,
  teamId?: string,
  shortName?: string
): string | null => {
  const slug = TEAM_LOGO_MAP[teamName] || (shortName && TEAM_LOGO_MAP[shortName]) || null;
  // Fixed: Point to public folder (accessible via URL)
  return slug ? `/Images/Club%20Logos/${slug}.png` : null;
};

export const getTeamLogo = (team: { name: string; shortName?: string; id?: string }) => {
  const logoPath = getTeamLogoPath(team.name, team.id, team.shortName);
  return {
    logoPath,
    fallbackInitial: team.shortName?.charAt(0) || team.name.charAt(0),
    fallbackName: team.shortName || team.name,
  };
};
