// scripts/rename-logos.js
// Run with: node scripts/rename-logos.js
const fs = require("fs");
const path = require("path");

const logosDir = path.join(__dirname, "../public/images/club-logos");
const outputFile = path.join(__dirname, "../src/utils/logoUtils.ts");

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, "and") // replace &
    .replace(/'/g, "") // remove apostrophes
    .replace(/\./g, "") // remove periods
    .replace(/\s+/g, "-") // spaces -> dashes
    .replace(/[^a-z0-9-]/g, ""); // strip anything else
}

// Collect mapping as we rename
const mapping = {};

fs.readdirSync(logosDir).forEach((file) => {
  const ext = path.extname(file); // .png
  const base = path.basename(file, ext); // "Arsenal FC"
  const slug = slugify(base); // "arsenal-fc"
  const newFile = `${slug}${ext}`;
  const oldPath = path.join(logosDir, file);
  const newPath = path.join(logosDir, newFile);

  // Rename file if necessary
  if (file !== newFile) {
    console.log(`Renaming: ${file} → ${newFile}`);
    fs.renameSync(oldPath, newPath);
  }

  // Add mapping
  mapping[base] = slug;
});

// Generate logoUtils.ts
const fileContent = `// ⚽ Auto-generated by scripts/rename-logos.js
// Do not edit this file manually — update logos in /public/images/club-logos instead

const TEAM_LOGO_MAP: Record<string, string> = ${JSON.stringify(mapping, null, 2)};

export const getTeamLogoPath = (
  teamName: string,
  teamId?: string,
  shortName?: string
): string | null => {
  let slug = TEAM_LOGO_MAP[teamName] || (shortName && TEAM_LOGO_MAP[shortName]) || null;
  return slug ? \`/images/club-logos/\${slug}.png\` : null;
};

export const getTeamLogo = (team: { name: string; shortName?: string; id?: string }) => {
  const logoPath = getTeamLogoPath(team.name, team.id, team.shortName);

  return {
    logoPath,
    fallbackInitial: team.shortName?.charAt(0) || team.name.charAt(0),
    fallbackName: team.shortName || team.name,
  };
};
`;

fs.writeFileSync(outputFile, fileContent, "utf8");

console.log(`✅ Renamed logos and updated ${outputFile}`);
