// scripts/rename-logos.js
// Run with: node scripts/rename-logos.js

const fs = require("fs");
const path = require("path");

const logosDir = path.join(__dirname, "../public/images/club-logos");
const outputFile = path.join(__dirname, "../src/utils/logoUtils.ts");

// Helper: slugify team names for filenames
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/'/g, "")
    .replace(/\./g, "")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// Manual alias overrides
const MANUAL_ALIASES = {
  "Man Utd": "manchester-united",
  "Man United": "manchester-united",
  "Spurs": "tottenham-hotspur",
  "Man City": "manchester-city",
  "Nott'm Forest": "nottingham-forest",
  "Wolves": "wolverhampton-wanderers",
  "Brighton": "brighton-and-hove-albion",
  "Leeds": "leeds-united",
  "West Ham": "west-ham-united",
  "Bournemouth": "afc-bournemouth",
};

const mapping = {};

// Step 1: rename files to slugs
fs.readdirSync(logosDir).forEach((file) => {
  const ext = path.extname(file); // e.g. ".png"
  const name = path.basename(file, ext); // e.g. "Arsenal FC"
  const slug = slugify(name); // e.g. "arsenal-fc"
  const oldPath = path.join(logosDir, file);
  const newPath = path.join(logosDir, `${slug}${ext}`);

  if (file !== `${slug}${ext}`) {
    console.log(`Renaming: ${file} → ${slug}${ext}`);
    fs.renameSync(oldPath, newPath);
  }

  // Add mapping: full name → slug
  mapping[name] = slug;

  // If name ends with FC/AFC, add shorter variant
  const short = name.replace(/\s+(FC|AFC)$/i, "");
  if (short !== name) {
    mapping[short] = slug;
  }
});

// Step 2: add manual aliases
for (const [alias, slug] of Object.entries(MANUAL_ALIASES)) {
  mapping[alias] = slug;
}

// Step 3: write logoUtils.ts
const fileContent = `// ⚽ Auto-generated by scripts/rename-logos.js
// Do not edit manually — update logos in /public/images/club-logos and re-run the script.

const TEAM_LOGO_MAP: Record<string, string> = ${JSON.stringify(mapping, null, 2)};

export const getTeamLogoPath = (
  teamName: string,
  teamId?: string,
  shortName?: string
): string | null => {
  const slug = TEAM_LOGO_MAP[teamName] || (shortName && TEAM_LOGO_MAP[shortName]) || null;
  return slug ? \`/images/club-logos/\${slug}.png\` : null;
};

export const getTeamLogo = (team: { name: string; shortName?: string; id?: string }) => {
  const logoPath = getTeamLogoPath(team.name, team.id, team.shortName);

  return {
    logoPath,
    fallbackInitial: team.shortName?.charAt(0) || team.name.charAt(0),
    fallbackName: team.shortName || team.name,
  };
};
`;

fs.writeFileSync(outputFile, fileContent, "utf8");
console.log(`✅ Logos renamed and mapping written to ${outputFile}`);
