name: Scrape FBref Fixtures

on:
  schedule:
    - cron: "15 22 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Compile scraper
        run: npx tsc scripts/scrapeFixtures.ts --outDir scripts/dist

      - name: Run compiled scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node --loader ts-node/esm scripts/dist/scrapeFixtures.js
