name: Scrape FBref Fixtures

on:
  schedule:
    - cron: "15 22 * * *" # runs daily at 22:15 UTC
  workflow_dispatch:       # lets you run manually from GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run scraper with ts-node
  env:
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  run: npx ts-node --esm scripts/scrapeFixtures.ts
