name: Scrape FBref Team Stats debug

on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push changes
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Compile scraper
        run: npx tsc --project tsconfig.scripts.json

      - name: Run compiled scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node dist/debugTeamStats.js

      - name: Commit scraped data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No changes in data/ to commit"
          else
            git commit -m "chore: update scraped data [skip ci]"
            git push
          fi
